### ISSUE TITLE
Node ID issues 

### ISSUE THREAD

**Issue by PoobalanS** [hbmartin/graphviz2drawio#101]
Hello @hbmartin , 

This library looks great, but there are some issues in converted MXGraph XML

XML file contain node id's like node1, node2  and node3 instead we would like to have exact node id from dot file

It would be great if you can help us on this

Thanks

**Comment by hbmartin** [comment]
Thanks for the feedback, I will investigate 👍

**Comment by hbmartin** [comment]
@PoobalanS this functionality appears to work for me. If I have the graph 

```
digraph G {
    // Graph attributes
    rankdir=LR;
    node [shape=circle];

    // Nodes with specified IDs
    node1 [id="start", label="Start"];
    node2 [id="process", label="Process"];
    node3 [id="decision", label="Decision", shape=diamond];
    node4 [id="end", label="End"];

    // Edges
    node1 -> node2;
    node2 -> node3;
    node3 -> node4 [label="Yes"];
    node3 -> node2 [label="No"];
}
```

I get the following:
<img width="551" alt="Screenshot 2024-10-04 at 2 42 02 PM" src="https://github.com/user-attachments/assets/b41a8f77-2709-4c5e-aa9a-4e4341ccb9ff">

Are you able to provide more details about your case? Or ideally a sample graph where this is not behaving as expected?

**Comment by PoobalanS** [comment]
I have attached the DOT file and output XML files as TXT files here

We have images as base64 here that too not rendering properly

[dot_files_as_txt.txt](https://github.com/user-attachments/files/17264791/dot_files_as_txt.txt)
[xm_file_as_txt.txt](https://github.com/user-attachments/files/17264792/xm_file_as_txt.txt)

**Comment by hbmartin** [comment]
@PoobalanS this dot file doesn't seem to be graphviz, when I run `dot -Tsvg dot_files_as_txt.txt` I get the error `Error: dot_files_as_txt.txt: syntax error in line 25 scanning a HTML string (missing '>'? bad nesting? longer than 16384?) String starting:<<TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0"><TR><TD FIXEDSIZE="TRUE" WIDTH=`

What tool are you using to create or visualize this graph? g2d cannot work on graphs that are not valid.

**Comment by PoobalanS** [comment]
@hbmartin, We are using the Digraph package from graphviz to create this circuit.  We also converted this Graph file into XML using graphviz2drawio library. Attached that output XML in previous message. can you try with graphviz2drawio library to convert into XML.

**Comment by hbmartin** [comment]
@PoobalanS how are you creating this graph? how are you visualizing it?

**Comment by PoobalanS** [comment]
@hbmartin We are using the Digraph package from graphviz in python to create this graph with HTML like tables methods for node creation and we download as svg to visualizing it.
