### ISSUE TITLE
UnicodeDecodeError when converting .dot file with graphviz2drawio

### ISSUE THREAD

**Issue by CongJie-Pan** [hbmartin/graphviz2drawio#105]
I encountered a `UnicodeDecodeError` when trying to convert a `.dot` file to `.drawio` (XML) format using `graphviz2drawio`. The error seems related to encoding issues, as it defaults to `cp950` encoding, which does not support certain characters in my `.dot` file.

---

### Steps to Reproduce:

1. Run the following command in Anaconda Prompt:
   ```bash
   graphviz2drawio moovoDOT.dot -o moovoDrawio.xml
   ```
2. Observe the following error message in the terminal.

---

### Error Message:

```
Error converting <_io.TextIOWrapper name='moovoDOT.dot' mode='r' encoding='cp950'>
Please open a report at
https://github.com/hbmartin/graphviz2drawio/issues
and include your diagram and the following error:

Python: 3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:20:11) [MSC v.1938 64 bit (AMD64)], g2d: 1.0.0
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\Scripts\graphviz2drawio-script.py", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\USER\anaconda3\Lib\site-packages\graphviz2drawio\__main__.py", line 61, in main
    _convert_file(in_file, args.program, out_file)
  File "C:\Users\USER\anaconda3\Lib\site-packages\graphviz2drawio\__main__.py", line 22, in _convert_file
    output = convert(to_convert.read(), program)
                     ^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'cp950' codec can't decode byte 0xe7 in position 308: illegal multibyte sequence
```

---

### Environment:

- **Python version**: 3.12.3 (Conda-forge package)
- **graphviz2drawio version**: 1.0.0
- **OS**: Windows 64-bit

---

### Additional Context:

The `.dot` file I am using contains UTF-8 encoded characters, which seems incompatible with the `cp950` encoding defaulted by `graphviz2drawio`.

### Troubleshooting Steps Attempted

I tried several steps to solve the issue on my own, including:

1. **Modifying the Encoding**: I saved the `.dot` file with UTF-8 encoding and attempted to specify UTF-8 directly in the code. However, the `graphviz2drawio` command still defaulted to `cp950`, and the error persisted.

2. **Using Alternative XML Parsers**: I attempted to work around this by trying XML parsing libraries such as `xmltodict`, but the issue with encoding was not resolved.

3. **Checking the System Configuration**: I verified that my system and Python installation supported UTF-8 encoding, and I confirmed that `graphviz` was properly installed and configured. 

Despite these steps, I was unable to resolve the issue and suspect that support for UTF-8 encoding in `graphviz2drawio` could address this problem.

---

### Attachment

Below is my `.dot` file for reference and python converting file:  
[moovoDOT.zip](https://github.com/user-attachments/files/17619793/moovoDOT.zip)
[convert_dot_to_drawio.zip](https://github.com/user-attachments/files/17626463/convert_dot_to_drawio.zip)

Thank you for your assistance.

---

**Comment by hbmartin** [comment]
Thank you for your detailed and thorough report. 
It surprises me that UTF-8 encoding is not being used, as I believe it is always the default for me.
Is it possible that there is a system or anaconda environment configuration forcing cp950?
In any case, I will investigate further tomorrow.

**Comment by hbmartin** [comment]
After looking into this, it seems that Python is detecting the encoding of the file as `cp950` when you want it to detect `utf-8`. I don't have access to Windows currently so I can't confirm this myself now but I will this weekend.
There are 2 ways I can think of to address this:
One, resave the dot file as utf-8 using [Notepad++ or iconv](https://superuser.com/questions/290593/how-to-convert-character-encodings-on-windows) or [powershell](https://www.powershelladmin.com/wiki/Convert_from_most_encodings_to_utf8_with_powershell.php).
Alternately you can try to use this snippet to force Python to read the file as utf-8 like this:
```
from graphviz2drawio import graphviz2drawio
from pathlib import Path
file = Path("D:\\關於大學\\大三\\系統分析與設計\\HW\\第六次作業\\moovoDOT.dot")
dot = file.read_text(encoding="utf-8")
xml = graphviz2drawio.convert(dot)
Path("D:\\關於大學\\大三\\系統分析與設計\\HW\\第六次作業\\moovoDrawio.xml").write_text(xml)
```
Let me know if either of these work for you, in the meantime here's the file I converted:
[moovoDOT.xml.zip](https://github.com/user-attachments/files/17654113/moovoDOT.xml.zip)

**Comment by CongJie-Pan** [comment]
Very Thanks to your adivice. I will try it today !

**Comment by CongJie-Pan** [comment]
Hello, I managed to resolve the issue through various troubleshooting steps today, and the problem have been solved, the xml file can actually be opened by the draw.io. So, I outlined my debugging process below.

The primary issues were encoding conflicts and missing dependencies, which were resolved by setting UTF-8 encoding and creating an isolated Conda environment with necessary GTK and Graphviz libraries.
---

## Detailed Issue Summary and Troubleshooting Process

### Issue 1: Encoding Error (`UnicodeDecodeError`)
   - **Problem**: When attempting to convert a `.dot` file, I received a `UnicodeDecodeError` due to the system defaulting to the `cp950` encoding, which doesn't support certain characters (specifically, Chinese characters) in the `.dot` file.
   - **Troubleshooting Steps**:
     - I tried saving the `.dot` file in UTF-8 encoding and modified the script to explicitly read the file as UTF-8. However, `graphviz2drawio` continued to default to `cp950`.
   - **Solution**: Forced UTF-8 encoding by directly specifying it in the code. Here’s the solution that worked:

     ```python
     from graphviz2drawio import graphviz2drawio
     from pathlib import Path

     # Read the .dot file with UTF-8 encoding
     file_path = Path("D:\\關於大學\\大三\\系統分析與設計\\HW\\第六次作業\\moovoDOT.dot")
     dot_content = file_path.read_text(encoding="utf-8")
     xml_content = graphviz2drawio.convert(dot_content)

     # Save XML with UTF-8 encoding to prevent character corruption
     output_path = Path("D:\\關於大學\\大三\\系統分析與設計\\HW\\第六次作業\\moovoDrawio.xml")
     output_path.write_text(xml_content, encoding="utf-8")
     ```

### Issue 2: Missing DLL Dependencies (`libintl_bindtextdomain` Error)
   - **Problem**: While running `xml_content = graphviz2drawio.convert(dot_content)` in the code line 7. I encountered the error open in a new error window :
   
     ```
     gdk_pixbuf-query-loaders.exe - Entry Point Not Found:
     The procedure entry point libintl_bindtextdomain could not be located in the dynamic link library 
     C:\Users\USER\anaconda3\Library\bin\gdk_pixbuf-2.0-0.dll.
     ```

   - **Troubleshooting Steps**:
     - I initially tried downloading and manually placing the `libintl-8.dll` file in the Anaconda `Library\bin` folder, and reinstall the anaconda. However, this did not resolve the issue.
     - I then decided to set up an isolated Conda environment with only the necessary dependencies to avoid potential conflicts , and that is the solution.
   - **Solution**: Created a new Conda environment with all required GTK and Graphviz dependencies, sourced from `conda-forge`:

     ```bash
     conda create -n gtk_env_new python=3.10
     conda activate gtk_env_new
     conda install -c conda-forge gtk3 gdk-pixbuf glib pango cairo libiconv gettext
     ```

   This solution resolved the `libintl_bindtextdomain` error, and `graphviz2drawio` ran successfully in the new environment.

### Issue 3: Runtime Warning (`Orthogonal edges do not handle edge labels`)
   - **Problem**: During the conversion process, a runtime warning appeared, stating that orthogonal edges do not handle edge labels correctly. This warning did not prevent conversion but may affect label display. Because it's just a warning, and it isn't affect the xml file result so I skip it. But below is the ChatGPT given solution.
   - **Troubleshooting Steps**:
     - I tested with various `.dot` files, confirming that the warning did not impact functionality.
   - **Solution**: Suppressed the warning to keep the output clean:

     ```python
     import warnings
     warnings.filterwarnings("ignore", category=RuntimeWarning)
     ```
---

## Environment Information

- **OS**: Windows 64-bit
- **Python Version**: 3.12.3 (Conda-forge package)
- **graphviz2drawio Version**: 1.0.0
- **Conda Environment**: Created specifically for this project with all dependencies managed through `conda-forge`.

---

## Steps to Reproduce Solution

1. **Force UTF-8 Encoding**: Use UTF-8 encoding for reading `.dot` files and writing `.drawio` XML files to prevent character corruption.
   
2. **Set up an Isolated Conda Environment**:
   - Use a dedicated Conda environment to avoid conflicts and manage `gtk3`, `gdk-pixbuf`, and other required libraries.

3. **Suppress Runtime Warnings**:
   - Use `warnings.filterwarnings` to suppress unnecessary warnings about orthogonal edge labels.

4. **Verify in Draw.io**:
   - Open the generated `.drawio` XML file in Draw.io to confirm the correct display of Chinese characters and ensure proper functionality.
