### ISSUE TITLE
raven

### ISSUE THREAD

**Issue by jcaplan** [hbmartin/graphviz2drawio#25]
what is raven? Are you collecting data from me? Did I consent to that?

**Comment by hbmartin** [comment]
raven is a crash logger, it saves the exception trace to sentry.io
no PII or graph data, I can send you an invite if you want to take a look
<img width="1594" alt="screenshot 2018-09-07 13 57 03" src="https://user-images.githubusercontent.com/745166/45242771-23382f00-b2a6-11e8-9481-009e2de8323b.png">

**Comment by jcaplan** [comment]
You didn't answer the question. Am I (or anybody else using this library) sending you crash reports without consent?

**Comment by hbmartin** [comment]
Sorry, I thought my answer was clear. The crash reports are automatically sent, unless you cancel by pressing ctrl-c. You can also uninstall raven to prevent crashes from being sent at all. Maybe there should also be a command line flag or something to turn this off.

**Comment by hbmartin** [comment]
@jcaplan made crash reporting optional in https://github.com/hbmartin/graphviz2drawio/commit/fd8560e316b5656d5044da3d408c66ee10603489
