### ISSUE TITLE
Crahses when open .dot file on Python 3.7

### ISSUE THREAD

**Issue by meinnamehier** [hbmartin/graphviz2drawio#27]
I try to open this file https://graphviz.gitlab.io/_pages/Gallery/directed/datastruct.gv.txt -> saved as test.dot using Python 3.7.1 on a Mac with MacOS 10.12.6

This is the error I get:

> This is beta software, please report issues to:
> https://github.com/hbmartin/graphviz2drawio/issues
> Something went wrong, please report
> Traceback (most recent call last):
>   File "/usr/local/bin/graphviz2drawio", line 10, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.7/site-packages/graphviz2drawio/__main__.py", line 26, in main
>     output = convert(args.to_convert, args.program)
>   File "/usr/local/lib/python3.7/site-packages/graphviz2drawio/graphviz2drawio.py", line 27, in convert
>     [e.enrich_from_graph(graph_edges[e.gid]) for e in edges]
>   File "/usr/local/lib/python3.7/site-packages/graphviz2drawio/graphviz2drawio.py", line 27, in <listcomp>
>     [e.enrich_from_graph(graph_edges[e.gid]) for e in edges]
> KeyError: 'node0:f0->node1:f0'
> Sentry is attempting to send 2 pending error messages
> Waiting up to 10 seconds
> Press Ctrl-C to quit

**Comment by hbmartin** [comment]
This is fixed in the upcoming 0.3 release and automated testing has been added for that file.
Feel free to reopen or create a new issue if that release does not work as you expect.
Thanks for the report!
