### ISSUE TITLE
fillcolor not refrected

### ISSUE THREAD

**Issue by raucha** [hbmartin/graphviz2drawio#42]
fillcolor not refrected

**Comment by jpcorbeil-nuance** [comment]
Is it solved? I also don't see my fillcolor reflected from the DOT file to the drawio one...

**Comment by hbmartin** [comment]
This is fixed in the upcoming 0.3 release and automated testing has been added for that file.
Feel free to reopen or create a new issue if that release does not work as you expect.
Thanks for the report!
