### ISSUE TITLE
Pip install pygraphviz fails on mac M1

### ISSUE THREAD

**Issue by squio** [hbmartin/graphviz2drawio#46]
The PIP command for installing `pygraphviz` on a macbook with the Arm M1 processor fails.

This command does work:

```sh
python3 -m pip  install  --global-option=build_ext \
  --global-option="-I/opt/homebrew/include"\
  --global-option="-L/opt/homebrew/lib"  pygraphviz 
```

I can create PR for README if you like

**Comment by hbmartin** [comment]
I updated instructions, feel free to comment or re-open if there's further improvements needed.
Thanks for reporting!
