### ISSUE TITLE
conversion fails on .dot file created by graphviz with python with a `path` shape

### ISSUE THREAD

**Issue by miladmahdavilayen** [hbmartin/graphviz2drawio#47]
I've created this file using graphviz in with python and it won't convert to .xml for drawio.
could only upload a compressed file. Dot not supported for upload here for some reasons.
[sensor_layout.zip](https://github.com/hbmartin/graphviz2drawio/files/8892773/sensor_layout.zip)

**Comment by abhiram2712** [comment]
Were there any workarounds for this? Experiencing the same issue and getting the error `list index out of range`. Also receiving warnings `node '*****', graph '****t' size too small for label`.

**Comment by hbmartin** [comment]
I was able to convert this without errors in the most recent release, please retry and let me know if there are any problems.

"size too small for label" is a a Graphviz warning and may indicate issues with your graph.
