### ISSUE TITLE
Add library functionality for output file

### ISSUE THREAD

**Issue by jredd96** [hbmartin/graphviz2drawio#97]
Hello, this is a very useful tool. I am hoping to be able to simply import the library to a python script and output the XML file just like on the commandline. 

For example, currrently the commandline syntax: `graphviz2drawio <filename>.dot`

Currently, `graphviz2drawio` is not callable, and graphviz2drawio.convert() simply returns a string that is not easily writeable. I am not quite skilled enough to submit a pull request to accomplish this, but it would allow graphviz2drawio to be integrated into scripting much better.

Desired library usage: `graphviz2drawio('<filename>.dot', '<out_file>.xml')` or maybe `graphviz2drawio.convert('<filename>.dot', '<out_file>.xml')` or something similar. 

Thanks!!

**Comment by hbmartin** [comment]
Hi @jredd96 👋 thanks for the feedback.

First, a quick answer to your question. After getting your xml string from g2d (as in the readme), here's how to write the file:

```
from pathlib import Path
Path("out_file.xml").write_text(xml)
```
(Side note, for questions like "how to write a string to a file in python" I've found that claude.ai and chatgpt quickly provide useful code.)

Re: adding a new method call, library authors (like me!) usually try to limit the public calls available. This is known as the "single responsibility principle" and applying it helps to keep code quality high while minimizing the maintenance burden.

Re: making a module itself callable, this isn't really possible in Python. It's an interesting idea that [has been discussed by Python's maintainers](https://discuss.python.org/t/pep-713-callable-modules/26127/1) but seems unlikely to happen.

**Comment by jredd96** [comment]
Thanks for your response @hbmartin! 

I suppose this shows my lack of skill... I did look into writing it to a file, but it was unclear whether g2d was returning a properly formatted string to write directly. Based on the readme, I wasn't sure.

Thanks again for the response!
