### ISSUE TITLE
Customisation request

### ISSUE THREAD

**Issue by Swathisri-02** [hbmartin/graphviz2drawio#98]
Hi there,

Your library works great on converting the dot file to xml one. But there are some main information missing in the xml file. My dot file contains image data which is not containing in the xml file during conversion.

How can I customise the tags in the xml along with my desired attributes so that it gives xml file without any manual interpretation ?

I also faced certain issues while converting a dot file containing b64 images into an xml file:

Error: syntax error in line 69 scanning a HTML string (missing '>'? bad nesting? longer than 16384?)
String starting:<<TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0"><TR><TD FIXEDSIZE="TRUE" WIDTH=
Error converting <_io.TextIOWrapper name='sample_diagram.dot' mode='r' encoding='UTF-8'>
Please open a report at
https://github.com/hbmartin/graphviz2drawio/issues
and include your diagram and the following error:

Python: 3.12.6 (main, Sep  6 2024, 19:03:47) [Clang 15.0.0 (clang-1500.3.9.4)], g2d: 1.0.0
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/graphviz2drawio/1.0.0/libexec/lib/python3.12/site-packages/pygraphviz/agraph.py", line 1251, in read
    self.handle = gv.agread(fh, None)
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/graphviz2drawio/1.0.0/libexec/lib/python3.12/site-packages/pygraphviz/graphviz.py", line 82, in agread
    return _graphviz.agread(input_file, arg2)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: agread: bad input data

Even after changing the string to certain characters, the xml does not contain the image data or its attributes

**Comment by hbmartin** [comment]
Hi @Swathisri-02 👋 

Are you able to provide an example to reproduce? I haven't seen b64 images embedded in a dot file before so not sure how to debug this.

There aren't any hooks to customize the output XML, if the image issues was fixed would you still need that?

**Comment by Swathisri-02** [comment]
<img width="1365" alt="b64 images embedded in a dot file" src="https://github.com/user-attachments/assets/8320ada5-bb41-4ca2-916a-431f5c03ddfe">

Hereby I have attached an image sample for a dot file with bd4 images embedded in it. How can I get that image information in an xml file ?

**Comment by hbmartin** [comment]
A screenshot of text is not useful. Please provide an example to reproduce in a dot file.

Was this generated with another diagramming software?

**Comment by Swathisri-02** [comment]
Will it be helpful if I produce a dit file itself ?

**Comment by hbmartin** [comment]
> Will it be helpful if I produce a dot file itself ?

Yes please

**Comment by Swathisri-02** [comment]
Hereby I will give a dot file where I could not render the b64 images in the xml format :

digraph "Wiring Diagram" {
	graph [bb="0,0,2829,889",
		nodesep=1,
		rankdir=LR,
		ranksep=8,
		splines=curved
	];
	node [label="\N"];
	subgraph cluster_rank_1 {
		graph [bb="8,217,179.5,409",
			rank=same,
			style=invis
		];
		DIM_D_ECU_ICU4M_1A	[height=0.84722,
			label=<<TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0"><TR><TD FIXEDSIZE="TRUE" WIDTH="127.52197265625" HEIGHT="49.125" ><IMG SRC="data:image/svg+xml,PD94bWwgdmVyc2lvbj0nMS4wJyBlbmNvZGluZz0nVVRGLTgnPz4KCjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgdmVyc2lvbj0iMS4xIiB2aWV3Qm94PSIgMCAwIDEyNy41MjE5NzI2NTYyNSA0OS4xMjUiIHdpZHRoPSIgMTI3LjUyMTk3MjY1NjI1IiBoZWlnaHQ9IiA0OS4xMjUiPgogIDxzdHlsZT50ZXh0IHsgZm9udC1mYW1pbHk6IEFyaWFsLCBzYW5zLXNlcmlmOyBmb250LXNpemU6IDdweDsgZm9udC13ZWlnaHQ6IDUwMDsgfTwvc3R5bGU+CiAgPGc+CiAgICA8Zz4KICAgICAgPHJlY3QgeD0iMCIgeT0iMC4zNzUiIHdpZHRoPSIxMTEuMDIxOTcyNjU2MjUiIGhlaWdodD0iNDguMzc1IiBmaWxsPSIjRkZGRkZGIiBzdHJva2U9ImJsYWNrIiBzdHJva2Utd2lkdGg9IjAuNzUiLz4KICAgICAgPGc+CiAgICAgICAgPGc+CiAgICAgICAgICA8dGV4dCBmb250LXNpemU9IjciIGZpbGw9ImJsYWNrIiBmb250LXdlaWdodD0iNTAwIiBmb250LWZhbWlseT0iY2FsaWJyaSIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMCA3KSIgeD0iOTcuNzE1MzMyMDMxMjUiIHk9IjEwLjM3NSI+RDE8L3RleHQ+CiAgICAgICAgICA8dGV4dCBmb250LXNpemU9IjciIGZpbGw9ImJsYWNrIiBmb250LXdlaWdodD0iNTAwIiBmb250LWZhbWlseT0iY2FsaWJyaSIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMCA3KSIgeD0iNSIgeT0iMTAuMzc1Ij4oKykgRlVFTCBMRVZFTDwvdGV4dD4KICAgICAgICA8L2c+CiAgICAgICAgPGc+CiAgICAgICAgICA8dGV4dCBmb250LXNpemU9IjciIGZpbGw9ImJsYWNrIiBmb250LXdlaWdodD0iNTAwIiBmb250LWZhbWlseT0iY2FsaWJyaSIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMCA3KSIgeD0iOTcuNzE1MzMyMDMxMjUiIHk9IjI5LjM3NSI+RDI8L3RleHQ+CiAgICAgICAgICA8dGV4dCBmb250LXNpemU9IjciIGZpbGw9ImJsYWNrIiBmb250LXdlaWdodD0iNTAwIiBmb250LWZhbWlseT0iY2FsaWJyaSIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMCA3KSIgeD0iNSIgeT0iMjkuMzc1Ij4oLSkgRlVFTCBMRVZFTDwvdGV4dD4KICAgICAgICA8L2c+CiAgICAgIDwvZz4KICAgIDwvZz4KICAgIDxnIHRyYW5zZm9ybT0idHJhbnNsYXRlKDExMS43NzE5NzI2NTYyNSwgMC4wKSBzY2FsZSgxIDEpICI+CiAgICAgIDxyZWN0IHg9IjAiIHk9IjAuMzc1IiB3aWR0aD0iMTUiIGhlaWdodD0iNDguMzc1IiBmaWxsPSIjRkZDMENCIiBzdHJva2U9ImJsYWNrIiBzdHJva2Utd2lkdGg9IjAuNzUiLz4KICAgICAgPGc+CiAgICAgICAgPHRleHQgZm9udC1zaXplPSI3IiBmaWxsPSJibGFjayIgZm9udC13ZWlnaHQ9IjUwMCIgZm9udC1mYW1pbHk9ImNhbGlicmkiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDAgNykiIHg9IjMuMzQ2Njc5Njg3NSIgeT0iMTAuMzc1Ij5EMTwvdGV4dD4KICAgICAgICA8dGV4dCBmb250LXNpemU9IjciIGZpbGw9ImJsYWNrIiBmb250LXdlaWdodD0iNTAwIiBmb250LWZhbWlseT0iY2FsaWJyaSIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMCA3KSIgeD0iMy4zNDY2Nzk2ODc1IiB5PSIyOS4zNzUiPkQyPC90ZXh0PgogICAgICA8L2c+CiAgICA8L2c+CiAgPC9nPgo8L3N2Zz4K" SCALE="BOTH"/></TD><TD FIXEDSIZE="TRUE" WIDTH="0" ALIGN="LEFT" VALIGN="BOTTOM"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" HEIGHT="49.125"><TR><TD PORT="D1" WIDTH="0" HEIGHT="0" ALIGN="LEFT" VALIGN="BOTTOM">&#183;</TD></TR><TR><TD PORT="D2" WIDTH="0" HEIGHT="0" ALIGN="LEFT" VALIGN="BOTTOM">&#183;</TD></TR></TABLE></TD></TR></TABLE>>,
			pos="93.75,370",
			shape=none,
			width=2.1597];
		MAIN_CAB_D_PDM	[height=0.58333,
			label=<<TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0"><TR><TD FIXEDSIZE="TRUE" WIDTH="111.1669921875" HEIGHT="30.125" ><IMG SRC="data:image/svg+xml,PD94bWwgdmVyc2lvbj0nMS4wJyBlbmNvZGluZz0nVVRGLTgnPz4KCjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgdmVyc2lvbj0iMS4xIiB2aWV3Qm94PSIgMCAwIDExMS4xNjY5OTIxODc1IDMwLjEyNSIgd2lkdGg9IiAxMTEuMTY2OTkyMTg3NSIgaGVpZ2h0PSIgMzAuMTI1Ij4KICA8c3R5bGU+dGV4dCB7IGZvbnQtZmFtaWx5OiBBcmlhbCwgc2Fucy1zZXJpZjsgZm9udC1zaXplOiA3cHg7IGZvbnQtd2VpZ2h0OiA1MDA7IH08L3N0eWxlPgogIDxnPgogICAgPGc+CiAgICAgIDxyZWN0IHg9IjAiIHk9IjAuMzc1IiB3aWR0aD0iOTQuNjY2OTkyMTg3NSIgaGVpZ2h0PSIyOS4zNzUiIGZpbGw9IiNGRkZGRkYiIHN0cm9rZT0iYmxhY2siIHN0cm9rZS13aWR0aD0iMC43NSIvPgogICAgICA8Zz4KICAgICAgICA8Zz4KICAgICAgICAgIDx0ZXh0IGZvbnQtc2l6ZT0iNyIgZmlsbD0iYmxhY2siIGZvbnQtd2VpZ2h0PSI1MDAiIGZvbnQtZmFtaWx5PSJjYWxpYnJpIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgwIDcpIiB4PSI4MS4zNjAzNTE1NjI1IiB5PSIxMC4zNzUiPkQ2PC90ZXh0PgogICAgICAgICAgPHRleHQgZm9udC1zaXplPSI3IiBmaWxsPSJibGFjayIgZm9udC13ZWlnaHQ9IjUwMCIgZm9udC1mYW1pbHk9ImNhbGlicmkiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDAgNykiIHg9IjUiIHk9IjEwLjM3NSI+SFRSIFNQTFk8L3RleHQ+CiAgICAgICAgPC9nPgogICAgICA8L2c+CiAgICA8L2c+CiAgICA8ZyB0cmFuc2Zvcm09InRyYW5zbGF0ZSg5NS40MTY5OTIxODc1LCAwLjApIHNjYWxlKDEgMSkgIj4KICAgICAgPHJlY3QgeD0iMCIgeT0iMC4zNzUiIHdpZHRoPSIxNSIgaGVpZ2h0PSIyOS4zNzUiIGZpbGw9IiM3MDgwOTAiIHN0cm9rZT0iYmxhY2siIHN0cm9rZS13aWR0aD0iMC43NSIvPgogICAgICA8Zz4KICAgICAgICA8dGV4dCBmb250LXNpemU9IjciIGZpbGw9ImJsYWNrIiBmb250LXdlaWdodD0iNTAwIiBmb250LWZhbWlseT0iY2FsaWJyaSIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMCA3KSIgeD0iMy4zNDY2Nzk2ODc1IiB5PSIxMC4zNzUiPkQ2PC90ZXh0PgogICAgICA8L2c+CiAgICA8L2c+CiAgPC9nPgo8L3N2Zz4K" SCALE="BOTH"/></TD><TD FIXEDSIZE="TRUE" WIDTH="0" ALIGN="LEFT" VALIGN="BOTTOM"><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" HEIGHT="30.125"><TR><TD PORT="D6" WIDTH="0" HEIGHT="0" ALIGN="LEFT" VALIGN="BOTTOM">&#183;</TD></TR></TABLE></TD></TR></TABLE>>,
			pos="93.75,246",
			shape=none,
			width=1.9375];
	}
	subgraph cluster_rank_2 {
		graph [bb="739.5,318,827.5,410",
			rank=same,
			style=invis
		];
		DASH_H_FW_VERT_1A	[height=1.0556,
			label=<<TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" ><TR><TD FIXEDSIZE="TRUE" WIDTH="0"  ><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" ><TR><TD PORT="48" WIDTH="0" HEIGHT="0" ALIGN="RIGHT">&#183;</TD></TR><TR><TD PORT="47" WIDTH="0" HEIGHT="0" ALIGN="RIGHT">&#183;</TD></TR><TR><TD PORT="64" WIDTH="0" HEIGHT="0" ALIGN="RIGHT">&#183;</TD></TR></TABLE></TD><TD FIXEDSIZE="TRUE" WIDTH="31.5" HEIGHT="68.125"><IMG SRC="data:image/svg+xml,PD94bWwgdmVyc2lvbj0nMS4wJyBlbmNvZGluZz0nVVRGLTgnPz4KCjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgdmVyc2lvbj0iMS4xIiB2aWV3Qm94PSIgMCAwIDMxLjUgNjguMTI1IiB3aWR0aD0iIDMxLjUiIGhlaWdodD0iIDY4LjEyNSI+CiAgPHN0eWxlPnRleHQgeyBmb250LWZhbWlseTogQXJpYWwsIHNhbnMtc2VyaWY7IGZvbnQtc2l6ZTogN3B4OyBmb250LXdlaWdodDogNTAwOyB9PC9zdHlsZT4KICA8Zz4KICAgIDxnPgogICAgICA8cmVjdCB4PSIwIiB5PSIwLjM3NSIgd2lkdGg9IjE1IiBoZWlnaHQ9IjY3LjM3NSIgZmlsbD0iI0Y4RjhGRiIgc3Ryb2tlPSJibGFjayIgc3Ryb2tlLXdpZHRoPSIwLjc1Ii8+CiAgICAgIDxnPgogICAgICAgIDx0ZXh0IGZvbnQtc2l6ZT0iNyIgZmlsbD0iYmxhY2siIGZvbnQtd2VpZ2h0PSI1MDAiIGZvbnQtZmFtaWx5PSJjYWxpYnJpIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgwIDcpIiB4PSIzLjIyNjA3NDIxODc1IiB5PSIxMC4zNzUiPjQ4PC90ZXh0PgogICAgICAgIDx0ZXh0IGZvbnQtc2l6ZT0iNyIgZmlsbD0iYmxhY2siIGZvbnQtd2VpZ2h0PSI1MDAiIGZvbnQtZmFtaWx5PSJjYWxpYnJpIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgwIDcpIiB4PSIzLjIyNjA3NDIxODc1IiB5PSIyOS4zNzUiPjQ3PC90ZXh0PgogICAgICAgIDx0ZXh0IGZvbnQtc2l6ZT0iNyIgZmlsbD0iYmxhY2siIGZvbnQtd2VpZ2h0PSI1MDAiIGZvbnQtZmFtaWx5PSJjYWxpYnJpIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgwIDcpIiB4PSIzLjcyNjA3NDIxODc1IiB5PSI0OC4zNzUiPjY0PC90ZXh0PgogICAgICA8L2c+CiAgICA8L2c+CiAgICA8ZyB0cmFuc2Zvcm09InRyYW5zbGF0ZSgxNS43NSwgMC4wKSBzY2FsZSgxIDEpICI+CiAgICAgIDxyZWN0IHg9IjAiIHk9IjAuMzc1IiB3aWR0aD0iMTUiIGhlaWdodD0iNjcuMzc1IiBmaWxsPSIjOTBFRTkwIiBzdHJva2U9ImJsYWNrIiBzdHJva2Utd2lkdGg9IjAuNzUiLz4KICAgICAgPGc+CiAgICAgICAgPHRleHQgZm9udC1zaXplPSI3IiBmaWxsPSJibGFjayIgZm9udC13ZWlnaHQ9IjUwMCIgZm9udC1mYW1pbHk9ImNhbGlicmkiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDAgNykiIHg9IjMuMjI2MDc0MjE4NzUiIHk9IjEwLjM3NSI+NDg8L3RleHQ+CiAgICAgICAgPHRleHQgZm9udC1zaXplPSI3IiBmaWxsPSJibGFjayIgZm9udC13ZWlnaHQ9IjUwMCIgZm9udC1mYW1pbHk9ImNhbGlicmkiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDAgNykiIHg9IjMuMjI2MDc0MjE4NzUiIHk9IjI5LjM3NSI+NDc8L3RleHQ+CiAgICAgICAgPHRleHQgZm9udC1zaXplPSI3IiBmaWxsPSJibGFjayIgZm9udC13ZWlnaHQ9IjUwMCIgZm9udC1mYW1pbHk9ImNhbGlicmkiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDAgNykiIHg9IjMuNzI2MDc0MjE4NzUiIHk9IjQ4LjM3NSI+NjQ8L3RleHQ+CiAgICAgIDwvZz4KICAgIDwvZz4KICA8L2c+Cjwvc3ZnPgo="/></TD><TD FIXEDSIZE="TRUE" WIDTH="0"  ><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0"><TR><TD PORT="48+R" WIDTH="0" HEIGHT="0" ALIGN="RIGHT">&#183;</TD></TR><TR><TD PORT="47+R" WIDTH="0" HEIGHT="0" ALIGN="RIGHT">&#183;</TD></TR><TR><TD PORT="64+R" WIDTH="0" HEIGHT="0" ALIGN="RIGHT">&#183;</TD></TR></TABLE></TD></TR></TABLE>>,
			pos="783.5,364",
			shape=none,
			width=1];
	}
	subgraph cluster_rank_3 {
		graph [bb="1387.5,319,1475.5,449",
			rank=same,
			style=invis
		];
		FW_H_CHAS_OPT	[height=1.5903,
			label=<<TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0" ><TR><TD FIXEDSIZE="TRUE" WIDTH="0"  ><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0"><TR><TD PORT="14" WIDTH="0" HEIGHT="0" ALIGN="RIGHT">&#183;</TD></TR><TR><TD PORT="13" WIDTH="0" HEIGHT="0" ALIGN="RIGHT">&#183;</TD></TR><TR><TD PORT="1" WIDTH="0" HEIGHT="0" ALIGN="RIGHT">&#183;</TD></TR><TR><TD PORT="2" WIDTH="0" HEIGHT="0" ALIGN="RIGHT">&#183;</TD></TR><TR><TD PORT="3" WIDTH="0" HEIGHT="0" ALIGN="RIGHT">&#183;</TD></TR></TABLE></TD><TD FIXEDSIZE="TRUE" WIDTH="31.5" HEIGHT="106.125"><IMG SRC="data:image/svg+xml,PD94bWwgdmVyc2lvbj0nMS4wJyBlbmNvZGluZz0nVVRGLTgnPz4KCjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgdmVyc2lvbj0iMS4xIiB2aWV3Qm94PSIgMCAwIDMxLjUgMTA2LjEyNSIgd2lkdGg9IiAzMS41IiBoZWlnaHQ9IiAxMDYuMTI1Ij4KICA8c3R5bGU+dGV4dCB7IGZvbnQtZmFtaWx5OiBBcmlhbCwgc2Fucy1zZXJpZjsgZm9udC1zaXplOiA3cHg7IGZvbnQtd2VpZ2h0OiA1MDA7IH08L3N0eWxlPgogIDxnPgogICAgPGc+CiAgICAgIDxyZWN0IHg9IjAiIHk9IjAuMzc1IiB3aWR0aD0iMTUiIGhlaWdodD0iMTA1LjM3NSIgZmlsbD0iI0QzRDNEMyIgc3Ryb2tlPSJibGFjayIgc3Ryb2tlLXdpZHRoPSIwLjc1Ii8+CiAgICAgIDxnPgogICAgICAgIDx0ZXh0IGZvbnQtc2l6ZT0iNyIgZmlsbD0iYmxhY2siIGZvbnQtd2VpZ2h0PSI1MDAiIGZvbnQtZmFtaWx5PSJjYWxpYnJpIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgwIDcpIiB4PSIzLjcyNjA3NDIxODc1IiB5PSIxMC4zNzUiPjE0PC90ZXh0PgogICAgICAgIDx0ZXh0IGZvbnQtc2l6ZT0iNyIgZmlsbD0iYmxhY2siIGZvbnQtd2VpZ2h0PSI1MDAiIGZvbnQtZmFtaWx5PSJjYWxpYnJpIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgwIDcpIiB4PSIzLjcyNjA3NDIxODc1IiB5PSIyOS4zNzUiPjEzPC90ZXh0PgogICAgICAgIDx0ZXh0IGZvbnQtc2l6ZT0iNyIgZmlsbD0iYmxhY2siIGZvbnQtd2VpZ2h0PSI1MDAiIGZvbnQtZmFtaWx5PSJjYWxpYnJpIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgwIDcpIiB4PSI1LjUiIHk9IjQ4LjM3NSI+MTwvdGV4dD4KICAgICAgICA8dGV4dCBmb250LXNpemU9IjciIGZpbGw9ImJsYWNrIiBmb250LXdlaWdodD0iNTAwIiBmb250LWZhbWlseT0iY2FsaWJyaSIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMCA3KSIgeD0iNS41IiB5PSI2Ny4zNzUiPjI8L3RleHQ+CiAgICAgICAgPHRleHQgZm9udC1zaXplPSI3IiBmaWxsPSJibGFjayIgZm9udC13ZWlnaHQ9IjUwMCIgZm9udC1mYW1pbHk9ImNhbGlicmkiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDAgNykiIHg9IjUuNSIgeT0iODYuMzc1Ij4zPC90ZXh0PgogICAgICA8L2c+CiAgICA8L2c+CiAgICA8ZyB0cmFuc2Zvcm09InRyYW5zbGF0ZSgxNS43NSwgMC4wKSBzY2FsZSgxIDEpICI+CiAgICAgIDxyZWN0IHg9IjAiIHk9IjAuMzc1IiB3aWR0aD0iMTUiIGhlaWdodD0iMTA1LjM3NSIgZmlsbD0iI0QzRDNEMyIgc3Ryb2tlPSJibGFjayIgc3Ryb2tlLXdpZHRoPSIwLjc1Ii8+CiAgICAgIDxnPgogICAgICAgIDx0ZXh0IGZvbnQtc2l6ZT0iNyIgZmlsbD0iYmxhY2siIGZvbnQtd2VpZ2h0PSI1MDAiIGZvbnQtZmFtaWx5PSJjYWxpYnJpIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgwIDcpIiB4PSIzLjcyNjA3NDIxODc1IiB5PSIxMC4zNzUiPjE0PC90ZXh0PgogICAgICAgIDx0ZXh0IGZvbnQtc2l6ZT0iNyIgZmlsbD0iYmxhY2siIGZvbnQtd2VpZ2h0PSI1MDAiIGZvbnQtZmFtaWx5PSJjYWxpYnJpIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgwIDcpIiB4PSIzLjcyNjA3NDIxODc1IiB5PSIyOS4zNzUiPjEzPC90ZXh0PgogICAgICAgIDx0ZXh0IGZvbnQtc2l6ZT0iNyIgZmlsbD0iYmxhY2siIGZvbnQtd2VpZ2h0PSI1MDAiIGZvbnQtZmFtaWx5PSJjYWxpYnJpIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgwIDcpIiB4PSI1LjUiIHk9IjQ4LjM3NSI+MTwvdGV4dD4KICAgICAgICA8dGV4dCBmb250LXNpemU9IjciIGZpbGw9ImJsYWNrIiBmb250LXdlaWdodD0iNTAwIiBmb250LWZhbWlseT0iY2FsaWJyaSIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMCA3KSIgeD0iNS41IiB5PSI2Ny4zNzUiPjI8L3RleHQ+CiAgICAgICAgPHRleHQgZm9udC1zaXplPSI3IiBmaWxsPSJibGFjayIgZm9udC13ZWlnaHQ9IjUwMCIgZm9udC1mYW1pbHk9ImNhbGlicmkiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDAgNykiIHg9IjUuNSIgeT0iODYuMzc1Ij4zPC90ZXh0PgogICAgICA8L2c+CiAgICA8L2c+CiAgPC9nPgo8L3N2Zz4K"/></TD><TD FIXEDSIZE="TRUE" WIDTH="0"  ><TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0"><TR><TD PORT="14+R" WIDTH="0" HEIGHT="0" ALIGN="RIGHT">&#183;</TD></TR><TR><TD PORT="13+R" WIDTH="0" HEIGHT="0" ALIGN="RIGHT">&#183;</TD></TR><TR><TD PORT="1+R" WIDTH="0" HEIGHT="0" ALIGN="RIGHT">&#183;</TD></TR><TR><TD PORT="2+R" WIDTH="0" HEIGHT="0" ALIGN="RIGHT">&#183;</TD></TR><TR><TD PORT="3+R" WIDTH="0" HEIGHT="0" ALIGN="RIGHT">&#183;</TD></TR></TABLE></TD></TR></TABLE>>,
			pos="1431.5,384",
			shape=none,
			width=1];
	}
	DIM_D_ECU_ICU4M_1A:D1 -> DASH_H_FW_VERT_1A:48	[arrowhead=none,
		constraint=true,
		pos="161.47,384.08 338.3,376.8 342.12,376.84 757.77,384.43",
		style=ortho];
	DIM_D_ECU_ICU4M_1A:D2 -> DASH_H_FW_VERT_1A:47	[arrowhead=none,
		constraint=true,
		pos="161.48,363.52 338.49,353.74 342.31,353.78 757.77,363.9",
		style=ortho];
	MAIN_CAB_D_PDM:D6 -> DASH_H_FW_VERT_1A:64	[arrowhead=none,
		constraint=true,
		pos="153.26,251.35 332.49,278.22 336.16,278.78 757.71,342.89",
		style=ortho];
	DASH_H_FW_VERT_1A:"48+R" -> FW_H_CHAS_OPT:1	[arrowhead=none,
		constraint=true,
		pos="809.26,383.99 988.32,361.04 991.92,361.13 1405.8,383.78"];
	DASH_H_FW_VERT_1A:"47+R" -> FW_H_CHAS_OPT:2	[arrowhead=none,
		constraint=true,
		pos="809.29,363.32 990.02,333.09 993.63,333.22 1405.8,363.21"];
	DASH_H_FW_VERT_1A:"64+R" -> FW_H_CHAS_OPT:3	[arrowhead=none,
		constraint=true,
		pos="809.34,342.67 992.08,305.51 995.72,305.66 1405.5,342.62"];
}

**Comment by hbmartin** [comment]
Thanks, what tool are you using to render/visualize this?
When I run this through `dot` I get an error `Error: No or improper image file`

**Comment by Swathisri-02** [comment]
Okay I would just provide the svg file for that respected image, because I have provided the b64 format of that. Actually the dot file with svg images encoded would be like this :
[Dot file (1).docx](https://github.com/user-attachments/files/17220071/Dot.file.1.docx)

Please replace the image path with these svg images:
[svg folder.zip](https://github.com/user-attachments/files/17220075/svg.folder.zip)
